AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  description

Globals:
  Function:
    Timeout: 30

Resources:
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: sam-echo-test
      StageName: v1
      EndpointConfiguration: REGIONAL
  
  SAMEchoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: echo
      Handler: echo
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /api/{proxy+}
            Method: get
            RestApiId: !Ref MyAPI
            Auth:
              ResourcePolicy:
                CustomStatements: [{
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": "execute-api:Invoke",
                  "Resource": "arn:aws:execute-api:ap-northeast-1:*:*/*",
                  "Condition": {
                    "IpAddress": {
                      "aws:SourceIp": "X.X.X.X/32"
                    }
                  } 
                }]
      #Environment:
      #  Variables:
      #    PARAM1: VALUE

